### ISSUE TITLE
Actor sheet header buttons don't glow on hover

### ISSUE THREAD

**Issue by schultzcole** [sdenec/tidy5e-sheet#263]
tidy5e 0.4.16, no other modules active

Normally the header buttons for sheets will glow red when the user hovers over them. This is not happening for actor sheets while tidy5e is active. This seems to be due to the following rule:

```css
.tidy5e.sheet.actor a:hover {
    text-shadow: none;
}
```

I think the intended rule is probably

```css
.tidy5e.sheet.actor .window-content a:hover {
    text-shadow: none;
}
```
