### ISSUE TITLE
Request - Ability to remove Electrum

### ISSUE THREAD

**Issue by w1face** [sdenec/tidy5e-sheet#316]
Pretty much as it says, can we have an option to remove the Electum box?

**Comment by sdenec** [comment]
This is such an edge case that I won't build a specific setting for this.
But with the next update you can use the "custom css" module to hide the EP-Box or any other if you wish to do so.
Enter:
```css
.tidy5e.sheet.actor .inventory-currency .currency-item.ep {
	display: none;
}
```
replace "ep" with any other denomination (pp,gp,ep,sp,cp) to hide that one instead.
The box will technically still be there and functional but hidden (menaing converting money might potentially put a value into this box).
