### ISSUE TITLE
[Feature Request] Hide Source column

### ISSUE THREAD

**Issue by krysztalzg** [sdenec/tidy5e-sheet#318]
Hey, would it be possible to add an option to hide the `Source` column? We have all the info in the item description and we really don't care what book it came from after we import features into the characters.

**Comment by sdenec** [comment]
I would suggest using the "custom css" module to hide the column if you wish to do so. It's easier than me building a way to hide the column and creating yet another setting most likely just for you.
In the mod simply add this to the code window:
```css
.tidy5e.sheet.actor .items-list .items-header-labels .items-header-feat-source,
.tidy5e.sheet.actor .list-layout .items-list .item-detail.item-source {
	display: none;
}
```
Hope this is a viable workaround for you :)
