### ISSUE TITLE
 [Feature Request] The ability to hide Electrum and/or Platinum pieces from the character sheets

### ISSUE THREAD

**Issue by ComedianTF2** [sdenec/tidy5e-sheet#348]
In my games, we don't use Electrum pieces, and so it would be nice if the Electrum currency field could be removed from the character sheet. Platinum is less used, and could be unnecessary for short one-shot sessions so that would also be handy to remove

**Comment by sdenec** [comment]
I won't build a setting for this. But you can use the "custom css" module to hide the EP-Box or any other/multiple if you wish to do so.
Enter:
```css
.tidy5e.sheet.actor .inventory-currency .currency-item.ep {
	display: none;
}
```
replace "ep" with any other denomination (pp,gp,ep,sp,cp) to hide that one instead.
Create a comma separated list if you want to hide multiple fields:
```css
.tidy5e.sheet.actor .inventory-currency .currency-item.ep,
.tidy5e.sheet.actor .inventory-currency .currency-item.pp {
	display: none;
}
```
The boxes will technically still be there and functional but hidden (meaning converting money might potentially put a value into this box).

Hope this helps to customize the sheet for your needs!
