### ISSUE TITLE
Action tab doesn't show d20 on hover

### ISSUE THREAD

**Issue by Astra901** [sdenec/tidy5e-sheet#506]
![KKZ8H2V](https://user-images.githubusercontent.com/104297659/164967532-5c647509-7358-4fb8-8f00-68b78e398618.png)

When hovering over actions using the "Character Actions 5e" module, the d20 which appears on all other tabs does not show on top of the image.

**Comment by kaelad02** [comment]
From what I can tell, this is the standard dnd5e hover CSS that changes the item's icon to a die when hovering over it.

```css
.dnd5e.sheet.actor .inventory-list .item .item-name.rollable:hover .item-image {
  background-image: url("../../icons/svg/d20-grey.svg") !important;
}
.dnd5e.sheet.actor .inventory-list .item .item-name.rollable .item-image:hover {
  background-image: url("../../icons/svg/d20-black.svg") !important;
}
```

The icon looks different in Tidy5e Sheet but I can't figure out where the CSS for that is. However, I did find this, which looks like it turns off the background image. This appears to be what happens when hovering over an item in the actions tab. I'm not sure why this happens in the Actions tab and not something like the Abilities tab though.

```css
.tidy5e.sheet.actor .list-layout .items-list .item:not(.context) .item-name.rollable:hover .item-image,
.tidy5e.sheet.actor .list-layout .items-list .item:not(.context) .item-name:hover .item-image {
  background-image: none !important;
}
```
