### ISSUE TITLE
[Feature Request] Disable curency converter for players

### ISSUE THREAD

**Issue by CaosFR** [sdenec/tidy5e-sheet#558]
Hi,

I would like to disable the "currency  converter" on the sheet of my players :

![image](https://user-images.githubusercontent.com/37581932/188137419-678dce30-82f6-4c47-abf8-cc28362a660d.png)

Is it possible only GM can be a bank and convert gold ?

Thanks

**Comment by sdenec** [comment]
you could use the custom css module to disable the currency converter for non gms.
you have to add this css rule to the module:
```css
.tidy5e-sheet:not(.isGM) .inventory-currency .currency-item.convert { display: none;}
```
that should hide the field for players but lets you still see and use it.
