### ISSUE TITLE
Temporary Max HP is not considered when limiting the current HP anymore

### ISSUE THREAD

**Issue by TyrasNistru** [sdenec/tidy5e-sheet#681]
For example, if I put that a character has 90 max HP, and put 10 in the +Max Field, the current HP field could reach 100HP. This is not working anymore, but the overlay in the character avatar shows that it is "wounded" (part of the avatar is colored red):

![Screenshot 2023-02-04 231223](https://user-images.githubusercontent.com/9531350/216797971-e5a29b9c-ab4c-4a99-94c5-7008efcb3092.png)

**Comment by p4535992** [comment]
I see what the problem is, but I verified that it has always worked that way even before 2.1.X so I'm not sure what you mean by "This is not working anymore" and i verified the same behaviour with the current standard sheet so maybe this is intentional ?
The correct nehaviour it's seem when you set the "Hp Max Temp" to update the "Hp Temp" field not the "Hp Field" directly for the calculation to work.

**Comment by TyrasNistru** [comment]
> I see what the problem is, but I verified that it has always worked that way even before 2.1.X so I'm not sure what you mean by "This is not working anymore" and i verified the same behaviour with the current standard sheet so maybe this is intentional ? The correct nehaviour it's seem when you set the "Hp Max Temp" to update the "Hp Temp" field not the "Hp Field" directly for the calculation to work.

That doesn't make sense at all. Temporary HP doesn't have a cap, and (as it should) ignores the temp max HP field. 

The Temp Max HP field is used for effects like the spell Aid, that increases the max HP in a way that the character can be healed up to that new amount (normal maxHP + tempMaxHP). That doesn't happen with temporary HP. Temporary HP lost is "lost forever", and cannot be healed, only regained by effects that grant temporary HP.

![image](https://user-images.githubusercontent.com/9531350/217120981-2ebf36ad-057f-4758-9a48-be1cbeeb108b.png)

**Comment by sdenec** [comment]
The equasion tries to incorporate hp.max aswell as tempMax. Maybe the calculations or values are stroed differently now?
```css
background: linear-gradient(
								-90deg,
								transparent 0%,
								transparent calc(100% - ((100% / ({{#if (eq system.attributes.hp.max 0)}} 1 {{else}} {{system.attributes.hp.max}} {{/if}} + {{#if system.attributes.hp.tempmax}}{{system.attributes.hp.tempmax}}{{else}}0{{/if}} )) * ({{system.attributes.hp.value}} + {{#if system.attributes.hp.temp}}{{system.attributes.hp.temp}}{{else}}0{{/if}})) ),
								 	rgba(0, 200, 0, 0.5) calc(100% - ((100% / ({{#if (eq system.attributes.hp.max 0)}} 1 {{else}} {{system.attributes.hp.max}} {{/if}} + {{#if system.attributes.hp.tempmax}}{{system.attributes.hp.tempmax}}{{else}}0{{/if}} )) * ({{system.attributes.hp.value}} + {{#if system.attributes.hp.temp}}{{system.attributes.hp.temp}}{{else}}0{{/if}})) ),
								 	rgba(0, 200, 0, 0.5) 100%);
```
