### ISSUE TITLE
Handle formatting for added Ability and Skill scores

### ISSUE THREAD

**Issue by hafdon** [sdenec/tidy5e-sheet#85]
I've found that if I add Ability scores to the game system (dnd5e), in this case a "Sanity" score, then the sheet will not display scores past the base 6, even if there is room in the window. Furthermore, if Skill scores are also added to the game system, in this case "Psychology", "Occult", etc, these do not render properly unless the "Traits" section is moved below the Resources display. (Otherwise, there is table overlap -- see the 2nd image). 

Granted, there is just barely enough of the clickable Ability score header to prompt a roll, but it's not ideal.

I'm on Foundry 0.6.6, using the desktop application on mac running 10.15

![image](https://user-images.githubusercontent.com/39073287/91733047-112cb680-eb77-11ea-88ce-e5d4bbe03d74.png)

![image](https://user-images.githubusercontent.com/39073287/91733316-5f41ba00-eb77-11ea-9dff-c9040580bed5.png)

**Comment by hafdon** [comment]
I didn't realize that the height of the Ability score section was fixed, since the Skills appear to be flexible. Manually changing this value to 400px did the trick

```css
/* Ability Scores */

.tidy5e.sheet.actor .ability-scores {
	display: flex;
  flex-direction: column;
  flex: 0 72px;
  border: 1px solid var(--default-faint-color);
  overflow: hidden;
  height: 326px;
  border: none;
  border-radius: 0;
}
```
